[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
ffi = false
fs_permissions = []

via_ir = true

# gas report
gas_reports = ["RagequitVault"]
